image: golang:1.9

stages:
- test

before_script:
- go get -u golang.org/x/lint/golint
- go get -u github.com/kardianos/govendor
- mkdir -p /go/src/github.com/partitio
- cp -r $CI_PROJECT_DIR /go/src/github.com/partitio/gonextcloud
- cd /go/src/github.com/partitio/gonextcloud
- sed -i -e 's/$NEXTCLOUD_URL/'${NEXTCLOUD_URL//\//\\/}'/g' config.yml
- sed -i -e 's/$NEXTCLOUD_PASSWORD/'${NEXTCLOUD_PASSWORD}'/g' config.yml
- make dep

unit_tests:
  stage: test
  tags:
  - docker
  script:
  - make test

race_detector:
  stage: test
  tags:
  - docker
  script:
  - make race

memory_sanitizer:
  stage: test
  tags:
  - docker
  script:
  - make msan

code_coverage:
  stage: test
  tags:
  - docker
  script:
  - make coverage

lint_code:
  stage: test
  tags:
  - docker
  script:
  - make lint