url: https://my.nextcloud.com
login: admin
password: mypassword
app-name: testapp
share-folder: /Documents
not-existing-user: this-user-should-not-exist
not-existing-group: this-group-should-not-exist